/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evoteorbit;

import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
/**
 *
 * @author Septian Ricky M
 */
public class Dashboard_Pilih extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard_Pilih
     */
    private int idCalon = 0,validationCount = 0;
    private Voter voter;
    private JDialog dialogButton;
    
    public Dashboard_Pilih(Voter vote) {
        initComponents();
        this.setLocationRelativeTo(null);
        voter = vote;
    }
    
    public void endVoteSession(){
        this.dispose();
        Splash splash = new Splash();
        splash.setVisible(true);
    }
    
    public void konfirmasiThrice(){
        int n = JOptionPane.showConfirmDialog(this,"Yakin Memilih Calon Ini?","Konfirmasi",
    JOptionPane.YES_NO_OPTION); //0 untuk YES 1 untuk NO
        System.out.println(n+" dan validasi "+validationCount);
        if(n==0){
            validationCount++;
            if(validationCount<=2){
            konfirmasiThrice();
            }else{
                System.out.println(validationCount+"-> validationCount");
            }
        }else if(n==1){
            validationCount=0;
            JOptionPane.showMessageDialog(null, "Silahkan Pertimbangkan Lagi");
        }
    }
    
    public void VoterMemilih(int calon){
        idCalon = calon;
        switch(idCalon){
            case 1:
                JOptionPane.showMessageDialog(null, "Kamu Telah Memilih Helmy");
                voter.setPilihan(1);
                voter.endVote();
                voter.printPilihan();
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Kamu Telah Memilih Daffa");
                voter.setPilihan(2);
                voter.endVote();
                voter.printPilihan();
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "Kamu Telah Memilih Ihsan");
                voter.setPilihan(3);
                voter.endVote();
                voter.printPilihan();
                break;
            default:
                JOptionPane.showMessageDialog(null, "Id Tidak Ditemukan");
        }
        endVoteSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        foto_ihsan = new javax.swing.JLabel();
        foto_helmy = new javax.swing.JLabel();
        foto_daffa = new javax.swing.JLabel();
        btn_pilih_ihsan = new javax.swing.JLabel();
        btn_visi_daffa = new javax.swing.JLabel();
        btn_pilih_daffa = new javax.swing.JLabel();
        btn_pilih_helmy = new javax.swing.JLabel();
        btn_visi_ihsan = new javax.swing.JLabel();
        btn_visi_helmy = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(41, 61, 107));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foto_ihsan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/IhsanBg.png"))); // NOI18N
        jPanel1.add(foto_ihsan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        foto_helmy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/HelmyBg.png"))); // NOI18N
        jPanel1.add(foto_helmy, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        foto_daffa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DaffaBg.png"))); // NOI18N
        jPanel1.add(foto_daffa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        btn_pilih_ihsan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_pilih_ihsan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonPilih.png"))); // NOI18N
        btn_pilih_ihsan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pilih_ihsanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pilih_ihsanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pilih_ihsanMouseExited(evt);
            }
        });
        jPanel1.add(btn_pilih_ihsan, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 170, -1));

        btn_visi_daffa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_visi_daffa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonVisiMisi.png"))); // NOI18N
        btn_visi_daffa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_visi_daffaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_visi_daffaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_visi_daffaMouseExited(evt);
            }
        });
        jPanel1.add(btn_visi_daffa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 170, -1));

        btn_pilih_daffa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_pilih_daffa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonPilih.png"))); // NOI18N
        btn_pilih_daffa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pilih_daffaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pilih_daffaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pilih_daffaMouseExited(evt);
            }
        });
        jPanel1.add(btn_pilih_daffa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 170, -1));

        btn_pilih_helmy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_pilih_helmy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonPilih.png"))); // NOI18N
        btn_pilih_helmy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pilih_helmyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pilih_helmyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pilih_helmyMouseExited(evt);
            }
        });
        jPanel1.add(btn_pilih_helmy, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 170, -1));

        btn_visi_ihsan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_visi_ihsan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonVisiMisi.png"))); // NOI18N
        btn_visi_ihsan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_visi_ihsanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_visi_ihsanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_visi_ihsanMouseExited(evt);
            }
        });
        jPanel1.add(btn_visi_ihsan, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 170, -1));

        btn_visi_helmy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_visi_helmy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonVisiMisi.png"))); // NOI18N
        btn_visi_helmy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_visi_helmyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_visi_helmyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_visi_helmyMouseExited(evt);
            }
        });
        jPanel1.add(btn_visi_helmy, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 170, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BackgroundPilih.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_visi_daffaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visi_daffaMouseEntered
        // Set Background
        btn_visi_daffa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonVisiMisiHover.png")));
    }//GEN-LAST:event_btn_visi_daffaMouseEntered

    private void btn_visi_daffaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visi_daffaMouseExited
        // Set Background
        btn_visi_daffa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonVisiMisi.png")));
    }//GEN-LAST:event_btn_visi_daffaMouseExited

    private void btn_pilih_daffaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pilih_daffaMouseEntered
        // Set Background
        btn_pilih_daffa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonPilihHover.png")));
    }//GEN-LAST:event_btn_pilih_daffaMouseEntered

    private void btn_pilih_daffaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pilih_daffaMouseExited
        // Set Background
        btn_pilih_daffa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonPilih.png")));
    }//GEN-LAST:event_btn_pilih_daffaMouseExited

    private void btn_pilih_ihsanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pilih_ihsanMouseEntered
        // Set Background
        btn_pilih_ihsan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonPilihHover.png")));
    }//GEN-LAST:event_btn_pilih_ihsanMouseEntered

    private void btn_pilih_ihsanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pilih_ihsanMouseExited
        // Set Background
        btn_pilih_ihsan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonPilih.png")));
    }//GEN-LAST:event_btn_pilih_ihsanMouseExited

    private void btn_pilih_helmyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pilih_helmyMouseEntered
        // Set Background
        btn_pilih_helmy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonPilihHover.png")));
    }//GEN-LAST:event_btn_pilih_helmyMouseEntered

    private void btn_pilih_helmyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pilih_helmyMouseExited
        // Set Background
        btn_pilih_helmy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonPilih.png")));
    }//GEN-LAST:event_btn_pilih_helmyMouseExited

    private void btn_visi_ihsanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visi_ihsanMouseEntered
        // Set Background
        btn_visi_ihsan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonVisiMisiHover.png")));
    }//GEN-LAST:event_btn_visi_ihsanMouseEntered

    private void btn_visi_ihsanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visi_ihsanMouseExited
        // Set Background
        btn_visi_ihsan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonVisiMisi.png")));
    }//GEN-LAST:event_btn_visi_ihsanMouseExited

    private void btn_visi_helmyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visi_helmyMouseEntered
        // Set Background
        btn_visi_helmy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonVisiMisiHover.png")));
    }//GEN-LAST:event_btn_visi_helmyMouseEntered

    private void btn_visi_helmyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visi_helmyMouseExited
       // Set Background
        btn_visi_helmy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ButtonVisiMisi.png")));
    }//GEN-LAST:event_btn_visi_helmyMouseExited

    private void btn_pilih_helmyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pilih_helmyMouseClicked
        konfirmasiThrice();
        if(validationCount==3){
            VoterMemilih(1);
        }
    }//GEN-LAST:event_btn_pilih_helmyMouseClicked

    private void btn_pilih_daffaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pilih_daffaMouseClicked
        konfirmasiThrice();
        if(validationCount==3){
            VoterMemilih(2);
        }
    }//GEN-LAST:event_btn_pilih_daffaMouseClicked

    private void btn_pilih_ihsanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pilih_ihsanMouseClicked
        konfirmasiThrice();
        if(validationCount==3){
            VoterMemilih(3);
        }
    }//GEN-LAST:event_btn_pilih_ihsanMouseClicked

    private void btn_visi_helmyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visi_helmyMouseClicked
        VisiMisiHelmy helmy = new VisiMisiHelmy();
        helmy.setVisible(true);
    }//GEN-LAST:event_btn_visi_helmyMouseClicked

    private void btn_visi_daffaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visi_daffaMouseClicked
        VisiMisiDaffa daffa = new VisiMisiDaffa();
        daffa.setVisible(true);
    }//GEN-LAST:event_btn_visi_daffaMouseClicked

    private void btn_visi_ihsanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visi_ihsanMouseClicked
        VisiMisiIhsan ihsan = new VisiMisiIhsan();
        ihsan.setVisible(true);
    }//GEN-LAST:event_btn_visi_ihsanMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Dashboard_Pilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Dashboard_Pilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Dashboard_Pilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Dashboard_Pilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Dashboard_Pilih().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel btn_pilih_daffa;
    private javax.swing.JLabel btn_pilih_helmy;
    private javax.swing.JLabel btn_pilih_ihsan;
    private javax.swing.JLabel btn_visi_daffa;
    private javax.swing.JLabel btn_visi_helmy;
    private javax.swing.JLabel btn_visi_ihsan;
    private javax.swing.JLabel foto_daffa;
    private javax.swing.JLabel foto_helmy;
    private javax.swing.JLabel foto_ihsan;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
